### ISSUE TITLE
elementView.positionRelative is not a function after migrating to 2.1.0

### ISSUE THREAD

**Issue by luis-carlos-campos** [clientIO/joint#579]
Hi there,

I noticed it was removed on release 2.1.0 but there are type script files that still have this method.

Was this removal intentionally or temporarily?
Is there anything else I can use to substitute positionRelative?

Thanks in advance,

**Comment by kumilingus** [comment]
Hi, that was intentionally. `positionRelative` supposed to be a private method. If that was/is part of the TS definition it's a mistake. We are still in the process of fine-tuning the definition files.

What was your use case? The attributes have been massively refactored in the latest version (keeping the backwards compatibility though). It's now possible to define your own attributes (not documented yet) and the calculation of relative attributes is improved (performance, bugs).

**Comment by luis-carlos-campos** [comment]
I fixed it already. I was wondering if I should change that method for another or just avoid using.
I appreciate your time.
Regards,
