### ISSUE TITLE
this._portPosition not a function

### ISSUE THREAD

**Issue by doender** [clientIO/joint#530]
I'm using JointJS 1.0.3 in angular 2. Using the follow module definition:

```
this.module = new joint.shapes.basic.TextBlock({
    position: { x: 100, y: 50 },
    size: { width: 85, height: 45 },
    attrs: {
        rect: {rx: 10, ry: 20}
    },
    ports: {
        groups: {
            in: {
                attrs: {
                     text: {fill: '#000000'},
                     circle: {fill: '#fff', stroke: '#cdcdcd', 'stroke-width': 2, magnet: true, r: 7}
                },
                position: 'top'
            },
            out: {
                attrs: {
                    text: {fill: '#000000'},
                    circle: {fill: '#fff', stroke: '#cdcdcd', 'stroke-width': 2, magnet: true, r: 7}
                },
                position: 'bottom',
                label: {position: 'outside'}
            }
        },
        items: [
            {
                id: 'in1',
                group: 'in'
            }
        ]
    }
});
```

I get the following error: `this._getPosition is not a function`.
It seems to have something to do with the port groups.

This used to work in 1.0.2, but I'm trying to load joint using the npm module with typescript definitions instead of external scripts.

**Comment by mahald** [comment]
yea just started to use it with angular 4.1 and the typedefinitions seems to be hardly lack of several functions and features.

**Comment by vtalas** [comment]
JointJS comes with own Typescript definition since v1.1. The problem you've described should be fixed
there. Also, there are some more TS based fixes on master branch (pre-1.2 version).
