### ISSUE TITLE
index.js does not work with browserify from v0.9.9

### ISSUE THREAD

**Issue by mike-goodwin** [clientIO/joint#339]
The changes made for v0.9.9 in `index.js` means you can no longer `require` the package using browserify. Previously `index.js ` simpy `require`'d the main `dist/joint.js` which meant that it bundled perfectly with browserify. Now it has some additional logic and the `require` is now using a variable path name, which breaks compatibility with browserify.

**Comment by chill117** [comment]
@mike-goodwin Could you provide some kind of code sample (or small sample project) that would show me how you're using joint with browserify? We have some tests for browserify, but they are clearly missing some use-case. I'd like to add a new test to catch the problem you have cited.

**Comment by mike-goodwin** [comment]
I installed jointjs using npm. Is have an application file app.js that i want to use to create a client side bundle.  App.js contains a single line:

`require('jointjs');`

If I then do `browserify app.js -o bundle.js` the output file looks like this:

```
(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){

},{}],2:[function(require,module,exports){
(function (__dirname){

'use strict';

var fs = require('fs');

var possiblePaths = ['./build/joint.js', './dist/joint.js'];
var filePath;

while ((filePath = possiblePaths.shift())) {

    try {
        fs.statSync(__dirname + '/' + filePath);
    } catch (error) {
        // Try another path.
        continue;
    }

    // Found a path that exists.
    break;
}

if (!filePath) {
    throw new Error('JointJS build file not found.');
}

module.exports = require(filePath);

}).call(this,"/node_modules\\jointjs")
},{"fs":1}],3:[function(require,module,exports){
require('jointjs');
},{"jointjs":2}]},{},[3]);
```

Basically it is the content of index.js. This fails at runtime because the paths `./build` and `./dist` do not exist.

Previously, the index.js contained only the `require` whcih was recursively processed by browserify so that the output file contained the main `.dist/joint.js` file.

I hope this is clear enough :)

**Comment by mike-goodwin** [comment]
This could be fixed (for me at least) by adding  `"main": "./dist/joint.min.js"` to `package.json`.

**Comment by chill117** [comment]
Thank you for the information. I will make the fix and add a new test to ensure that JointJS continues to function with browserify in the future.

**Comment by chill117** [comment]
This has been fixed in [v0.9.10](https://github.com/clientIO/joint/releases/tag/v0.9.10)
