### ISSUE TITLE
after upgrading rappid 1.7 to 2.0.1 - this.renderMarkup is not a function error getting when tried to link element 

### ISSUE THREAD

**Issue by sshelake123** [clientIO/joint#522]
after upgrading rappid 1.7 to 2.0.1 - this.renderMarkup is not a function error getting when tried to link element 

can anyone help me

**Comment by kumilingus** [comment]
Can you please give us some more info? The stack trace and the class definition of your shape you getting the error for? Cheers.
